# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [published]
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Make Promotable
      run: mvn -X promote:prepare

    - name: Promote
      if: github.event_name == 'release'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "🤖 GitHub Actions"
        mvn -X release:prepare -Dtag=HEAD -DreleaseVersion=${{ github.event.release.tag_name }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
